// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.1
// source: settings.proto

package settings

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SettingsReaderClient is the client API for SettingsReader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SettingsReaderClient interface {
	Get(ctx context.Context, in *SettingsReq, opts ...grpc.CallOption) (*SettingsResp, error)
	Gets(ctx context.Context, in *SettingsMultiReq, opts ...grpc.CallOption) (*SettingsMultiResp, error)
}

type settingsReaderClient struct {
	cc grpc.ClientConnInterface
}

func NewSettingsReaderClient(cc grpc.ClientConnInterface) SettingsReaderClient {
	return &settingsReaderClient{cc}
}

func (c *settingsReaderClient) Get(ctx context.Context, in *SettingsReq, opts ...grpc.CallOption) (*SettingsResp, error) {
	out := new(SettingsResp)
	err := c.cc.Invoke(ctx, "/settings.settingsReader/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingsReaderClient) Gets(ctx context.Context, in *SettingsMultiReq, opts ...grpc.CallOption) (*SettingsMultiResp, error) {
	out := new(SettingsMultiResp)
	err := c.cc.Invoke(ctx, "/settings.settingsReader/Gets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SettingsReaderServer is the server API for SettingsReader service.
// All implementations must embed UnimplementedSettingsReaderServer
// for forward compatibility
type SettingsReaderServer interface {
	Get(context.Context, *SettingsReq) (*SettingsResp, error)
	Gets(context.Context, *SettingsMultiReq) (*SettingsMultiResp, error)
	mustEmbedUnimplementedSettingsReaderServer()
}

// UnimplementedSettingsReaderServer must be embedded to have forward compatible implementations.
type UnimplementedSettingsReaderServer struct {
}

func (UnimplementedSettingsReaderServer) Get(context.Context, *SettingsReq) (*SettingsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedSettingsReaderServer) Gets(context.Context, *SettingsMultiReq) (*SettingsMultiResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Gets not implemented")
}
func (UnimplementedSettingsReaderServer) mustEmbedUnimplementedSettingsReaderServer() {}

// UnsafeSettingsReaderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SettingsReaderServer will
// result in compilation errors.
type UnsafeSettingsReaderServer interface {
	mustEmbedUnimplementedSettingsReaderServer()
}

func RegisterSettingsReaderServer(s grpc.ServiceRegistrar, srv SettingsReaderServer) {
	s.RegisterService(&SettingsReader_ServiceDesc, srv)
}

func _SettingsReader_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettingsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingsReaderServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/settings.settingsReader/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingsReaderServer).Get(ctx, req.(*SettingsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettingsReader_Gets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettingsMultiReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingsReaderServer).Gets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/settings.settingsReader/Gets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingsReaderServer).Gets(ctx, req.(*SettingsMultiReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SettingsReader_ServiceDesc is the grpc.ServiceDesc for SettingsReader service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SettingsReader_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "settings.settingsReader",
	HandlerType: (*SettingsReaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _SettingsReader_Get_Handler,
		},
		{
			MethodName: "Gets",
			Handler:    _SettingsReader_Gets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "settings.proto",
}
